### ISSUE TITLE
ExcelScript.PivotHierarchy in the API documentation but isn't recognized?

### ISSUE THREAD

**Issue by nancy-wang** [OfficeDev/office-scripts-docs-reference#103]
Received this feedback from an Office Scripts user: https://www.reddit.com/r/excel/comments/n25gvp/excelscriptpivothierarchy_in_the_api/?utm_source=share&utm_medium=web2x&context=3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75751659-671e-f2ee-476b-8104f44d617f
* Version Independent ID: 08a70f2d-1a0f-8af1-a261-077a1fe8f071
* Content: [ExcelScript.PivotHierarchy interface - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.pivothierarchy?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.pivothierarchy.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.pivothierarchy.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
According to the reddit thread, this was a misunderstanding with the recorder, rather than an API issue. Closing this issue, with the note that the PivotTable APIs are generally confusing.
