### ISSUE TITLE
The description of the Excel.Range.setValues API is incorrect

### ISSUE THREAD

**Issue by yutao-huang** [OfficeDev/office-scripts-docs-reference#115]
The description of the `Excel.Range.setValues` is incorrect. It appears to be completely copied from the description of `Excel.Range.getValues`.

For example, `setValues` doesn't have return value, but the description states "*... the returned value...*".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcd3b516-e875-6dcf-6c57-81c7999548db
* Version Independent ID: fc09db9d-2b47-61a9-0dc6-fbd7a955cdc5
* Content: [ExcelScript.Range interface - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.range?view=office-scripts#setValues_values_)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @yutao-huang. Since these reference documents are generated from the type definition files for Office Scripts, I'll have to change those in the product. I'll contact the feature team and start that process.

**Comment by AlexJerabek** [comment]
This should be fixed with #122. Please let me know if you have any other concerns. Thanks!
