### ISSUE TITLE
What's 'inconsistent' & 'mixedCriteria' ?

### ISSUE THREAD

**Issue by YeeJone** [OfficeDev/office-scripts-docs-reference#118]
Judging from the document description, I can’t understand the meaning of these two types....
I didn’t find the corresponding entry in the Excel application...
Are there examples of these two types?
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55ff82ab-d404-bbae-5d0c-f85b8b61c3cf
* Version Independent ID: 9394998a-d246-2cd7-6a4d-c046f5f354ec
* Content: [ExcelScript.DataValidationType enum - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.datavalidationtype?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationtype.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.datavalidationtype.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @YeeJone,

Thanks for the question. I'm going to write up an example today and share it with you. Basically, neither of these values will never be explicitly set by a script. For both, they are the results of read operations on ranges with existing data validation rules. 

The following script tells you DataValidationType of the selected range. If you select multiple cells with different validation rules (like one uses "Number" and the other uses "List"), you'll get "Inconsistent".

```TypeScript
function main(workbook: ExcelScript.Workbook) {
  let range = workbook.getSelectedRange();
  console.log(range.getDataValidation().getType());
}
```

**Comment by AlexJerabek** [comment]
Also @YeeJone, is there a particular scenario you're trying to complete? Or are you just learning about the details of data validation?

**Comment by AlexJerabek** [comment]
I added a sample (#119) showing how to access this enum and added another phrasing to clear up the confusion between `incosistent` and `mixedCriteria`. Hopefully that helps, but please let me know if it doesn't.

However, I think that in looking into this, I may have found an issue in the JavaScript code. It seems like `inconsistent` is being returned when `mixedCriteria` should be instead. I've opened an [internal work item](https://office.visualstudio.com/OC/_workitems/edit/5259090) to track this investigation and will report back here as I learn things.

**Comment by YeeJone** [comment]
@AlexJerabek 
Thank you for your reply. I probably understand what circumstances these two types will appear...
From the above description, these two types will only be applied in the code? Will there be these two types in an Excel exported XML file?

**Comment by AlexJerabek** [comment]
Hi @YeeJone,

If I understand your question correctly, yes, these types are only in code. They are not a type of data validation, but rather the return value for multiple types of data validation are applied on the selected range.

Do you have any other questions, or should I close this issue?

**Comment by YeeJone** [comment]
> Hi @YeeJone,
> 
> If I understand your question correctly, yes, these types are only in code. They are not a type of data validation, but rather the return value for multiple types of data validation are applied on the selected range.
> 
> Do you have any other questions, or should I close this issue?

Thanks～
