### ISSUE TITLE
Office script docs lack examples

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-scripts-docs-reference#121]
I'd like to see simple -relevant- example code for every property and method on this page!
J.K. Pieterse
Office Apps & Services MVP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebeef4cb-bee7-fe65-eb57-1bc82057ef02
* Version Independent ID: c428326c-c428-6147-970a-439ffd988768
* Content: [ExcelScript.Chart interface - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.chart?view=office-scripts#getSeries__)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.chart.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.chart.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jkpieterse,

Thanks for your interest in Office Scripts sample code. We are working on increasing the amount of API reference samples, though there is a lot of ground to cover before we have complete coverage. 

Are there particular properties or methods that you're using in your scenario? I'd like to help by starting with the samples most relevant to you.

**Comment by jkpieterse** [comment]
Hi Alex,

 

No special requirements, I just happened to want to try changing the source data of a single chart series and could not find a reference as to how to address a chart series, either by name or by index. The intellisense also does not help much with things like that.

 

Regards,

 

Jan Karel Pieterse

JKP Application Development Services

The Netherlands

Chamber of Commerce # 12052177

https://www.jkp-ads.com

Phone: +31 495 750546

Mobile: +31 648 628252

**Comment by AlexJerabek** [comment]
Hi @jkpieterse,

I added some short, basic samples around ChartSeries in PR #124. If you ever have confusion with an API, please raise another issue and we'll happily make more sample code (or improve existing code). It helps to know which APIs are most impactful to you and the other Office Scripts users.

**Comment by jkpieterse** [comment]
Hi Alex

 

That looks very useful!

 

Regards,

 

Jan Karel Pieterse

Excel MVP

**Comment by AlexJerabek** [comment]
Closing this issue with PR #124. Please let me know if there are other scenarios needing more sample content.
