### ISSUE TITLE
nit: Typo in the description for parameter `fittingMode` of the `Chart.getImage` API

### ISSUE THREAD

**Issue by yutao-huang** [OfficeDev/office-scripts-docs-reference#128]
There seems to be a typo in the description for parameter `fittingMode` of the `Chart.getImage` API:

> Optional. The method used to scale the chart to the specified ***to the specified*** dimensions (if both height and width are set).

`to the specified` is repeated in this sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebeef4cb-bee7-fe65-eb57-1bc82057ef02
* Version Independent ID: c428326c-c428-6147-970a-439ffd988768
* Content: [ExcelScript.Chart interface - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.chart?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.chart.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.chart.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @yutao-huang. I'll make the change here and in the source code.
