### ISSUE TITLE
Typo in TableStyle.SetName

### ISSUE THREAD

**Issue by OneGitHubUsername** [OfficeDev/office-scripts-docs-reference#186]
Wrong description on TableStyle.SetName
Says "Gets the name of the table style." Should be "Sets..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9462c74d-af0a-fe2d-800f-649a5b6d2c4f
* Version Independent ID: fc870e57-03ed-887d-6044-c34dac8f1c68
* Content: [ExcelScript.TableStyle interface - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.tablestyle?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.tablestyle.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.tablestyle.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @OneGitHubUsername for pointing this out. I'll get that addressed in the IntelliSense file and the docs.
