### ISSUE TITLE
Handle timeout for bulk deletion of records from excel online using script

### ISSUE THREAD

**Issue by dipteshbose** [OfficeDev/office-scripts-docs-reference#214]
[Enter feedback here]
Please provide a workaround for handling timeout issue related to deleting multiple records in excel online. Power Automate does not have a straightforward delete all from an excel table connector. Even the script restricts because of the timeout issue. 

https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.table?view=office-scripts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c6501a0-4fda-c9b8-0142-0ecc19c432d0
* Version Independent ID: 54739f18-21a3-da30-3d29-813a225baa2f
* Content: [ExcelScript.Table interface - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.table?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.table.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.table.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @dipteshbose,

Thanks for reaching out. There are a few possibilities for getting your script to work within the [time limits of Power Automate](https://docs.microsoft.com/en-us/office/dev/scripts/testing/platform-limits#power-automate).

1. [Improve the performance of your script by avoiding read operations in a loop](https://docs.microsoft.com/en-us/office/dev/scripts/develop/web-client-performance#performance-optimizations).
2. Use the [Range.getSpecialCells API](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.range?view=office-scripts#excelscript-excelscript-range-getspecialcells-member(1)) to target larger numbers of cells as a bulk operation.
3. Call the script from Power Automate in a loop. I've previously described how to do this for the CSV parsing sample. My solution is here: https://github.com/OfficeDev/office-scripts-docs/issues/470#issuecomment-1090657702.

It's hard to tell which solution is most applicable for you without knowing your scenario. If you're able to provide your script, or describe what you're attempting to do, I can provide more help.
