### ISSUE TITLE
Placement values are incorrect

### ISSUE THREAD

**Issue by torresbj** [OfficeDev/office-scripts-docs-reference#229]
[Enter feedback here]

When I am running the setPlacement method, there's inconsistency from the documentation and the result. 

![image](https://user-images.githubusercontent.com/12954079/202070609-319f099a-193d-469a-ad9f-9287571ded8d.png)

oneCell is documented as moved and sized with cells but the actual effect is move but don't size with cells. 
twoCell is documented as moved with cells but the actual effect is moved and sized with cells. 

oneCell and twoCell are interchanged

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42ca1953-5e59-da07-42c8-148f79ef0dc9
* Version Independent ID: 728d27f6-ba71-9054-a816-b4d448ee724c
* Content: [ExcelScript.Placement enum - Office Scripts](https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.placement?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.placement.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.placement.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for letting us know. I'll verify that and get the documentation fixed.
