### ISSUE TITLE
getUsedRange throws error, not return "undefined" as in docs

### ISSUE THREAD

**Issue by sdudnic** [OfficeDev/office-scripts-docs-reference#233]
The problem is with the function **getUsedRange** of a Range. 

<html>
<body>

getUsedRange(valuesOnly) | Returns the used range of the given range object. If there are no used cells within the range, then this method returns undefined.
-- | --

</body>
</html>

When there is an empty range calling that function, it does not return undefined, as mentioned in the documentation, but throws an "RichApi.Error":

```
name: "RichApi.Error"
code: "ItemNotFound"
traceMessages: Array[0]
innerError: null
debugInfo: Object
code: "ItemNotFound"
message: "The requested resource doesn't exist."
toString: function toString()
errorLocation: "Range.getUsedRange"
statement: "var usedRange1 = range3.getUsedRange(...);"

```
PS. I remark **another** doc page on the same subject _this one is correct_
https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dcd3b516-e875-6dcf-6c57-81c7999548db
* Version Independent ID: fc09db9d-2b47-61a9-0dc6-fbd7a955cdc5
* Content: [ExcelScript.Range interface - Office Scripts](https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.range?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**[getUsedRange(valuesOnly)](https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.range?view=office-scripts#excelscript-excelscript-range-getusedrange-member(1))	
Returns the used range of the given range object. If there are no used cells within the range, then this method returns undefined.

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @sdudnic.

I'll update the Office Scripts documentation. Let me also tag @wandyezj to confirm this is the correct behavior from the product standpoint.
