### ISSUE TITLE
Update getCommentbyCell description to document error behaviour 

### ISSUE THREAD

**Issue by apcsb** [OfficeDev/office-scripts-docs-reference#271]
The GetCommentByCell will throw a breaking error "getCommentByCell: The requested resource doesn't exist." if the comment does not exist at the target cell, instead of returning null (as expected from getter methods). 
Please document this behavior or log a bug with the developers if this is a bug

https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.worksheet?view=office-scripts#excelscript-excelscript-worksheet-getcommentbycell-member(1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 452a5c69-ca1a-0b0a-9fba-d15a6587389d
* Version Independent ID: 9eb41033-a651-16b1-7349-3861607d7721
* Content: [ExcelScript.Worksheet interface - Office Scripts](https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.worksheet?view=office-scripts#excelscript-excelscript-worksheet-getcommentbycell-member(1))
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.worksheet.yml)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by isabela-dominguez** [comment]
@apcsb thank you for reaching out.

@alison-mk would you please be able to investigate this issue also related to GetCommentByCell?

**Comment by alison-mk** [comment]
Hi @apcsb, thanks for reporting this issue. I'm researching it internally. I'll report back when I have more information. 

Alison
