### ISSUE TITLE
fillFormats definition error

### ISSUE THREAD

**Issue by infohen** [OfficeDev/office-scripts-docs-reference#282]
Fields >> fillFormats | Populates the adjacent cells with the selected formulas.

(a) Shouldn't "... selected formulas" be "...selected formats"? 
(b) Is there a field for fillFormulas that "Populates the adjacent cells with the selected formulas."?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9b0676-983a-9a9c-202f-b6545da82ca2
* Version Independent ID: 4b5c7c5a-ec7a-87be-7477-a26f5bbe3edb
* Content: [ExcelScript.AutoFillType enum - Office Scripts](https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.autofilltype?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.autofilltype.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.autofilltype.yml)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @infohen,

Thanks for reporting this typo. `fillFormats` should be described as populating the adjacent cells with the selected formats.

There isn't an option for formulas. However, `fillCopy` provides the same functionality for formulas as it does with values.

**Comment by AlexJerabek** [comment]
The live site should be updated with this change tomorrow.

**Comment by infohen** [comment]
Thanks so much.
