### ISSUE TITLE
add repeat item labels in a PivotTable office script

### ISSUE THREAD

**Issue by mspowerplateform** [OfficeDev/office-scripts-docs-reference#296]
I need all item labels to repeat for the table to populate correctly. we can do it manually via the settings but need to be able to do it via office script.
 
 link : [https://learn.microsoft.com/en-us/answers/questions/1306576/add-repeat-item-labels-in-a-pivottable-office-scri](https://learn.microsoft.com/en-us/answers/questions/1306576/add-repeat-item-labels-in-a-pivottable-office-scri)

**Comment by AlexJerabek** [comment]
Hi @mspowerplateform,

Thank you for requesting a PivotTable sample. I'm going to investigate if this is supported by Office Scripts.

**Comment by AlexJerabek** [comment]
Hi @mspowerplateform,

This feature is not currently supported by Office Scripts (or the Office.js layer of Office Add-ins). I have created an issue with the product team (internal work item 8458277). 

We do not have a set timeline for when this will be evaluated and, if approved, added to Scripts. As such, I'm going to close this issue. The comment thread will stay open and I'll continue to watch it, in case you have other follow-ups.
