### ISSUE TITLE
No documentation usage or examples of usage for documentReference.

### ISSUE THREAD

**Issue by AwesomeParley** [OfficeDev/office-scripts-docs-reference#323]
**Link to page with issue**
[Documentation for RangeHyperlink documentReference](https://learn.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.rangehyperlink?view=office-scripts#excelscript-excelscript-rangehyperlink-documentreference-member)

**Issue**
No documentation usage or examples of usage for documentReference.
all it says is `documentReference?: string;` 
What should be put in the string?

**Screenshots**

What should be put in the string?
![image](https://github.com/OfficeDev/office-scripts-docs-reference/assets/90052285/2e69a072-01d2-43fd-8bdd-f62e1b64764b)

Why is there no Example of use in the example section?
![image](https://github.com/OfficeDev/office-scripts-docs-reference/assets/90052285/b5400309-35d9-4cb8-9215-3eea750720f8)

**Comment by AlexJerabek** [comment]
Hi @AwesomeParley,
 
Thanks for raising this issue. `address` and `documentReference` are used in different circumstances and wouldn't both be set for the same hyperlink. `address` sends the user to an external URL. `documentReference` sends the user to a place in the workbook.

You can see an example of `documentReference` used in the [Create a workbook table of contents sample](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/table-of-contents?view=office-scripts).

I'll add a sample in the reference documentation that illustrates how to use this property.

**Comment by AlexJerabek** [comment]
I realize I didn't explicitly answer your question. The string for `documentReference` should be any valid Excel address. The table of contents sample uses a worksheet name and cell address. The sample in PR #324 uses a table name.

**Comment by AwesomeParley** [comment]
> I realize I didn't explicitly answer your question. The string for `documentReference` should be any valid Excel address. The table of contents sample uses a worksheet name and cell address. The sample in PR #324 uses a table name.

Alright thanks! I was able to use the resources you sent to understand how to make my program work. Have a great day!

**Comment by AlexJerabek** [comment]
Great to hear! I'll close this issue once the new sample is checked in.
