### ISSUE TITLE
how to bind to an event

### ISSUE THREAD

**Issue by abiarge** [OfficeDev/office-scripts-docs-reference#39]
Hi,
it's not documented how to bind to events such as onChanged. If it's not supported, when? I find it essential to build automations....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76ccbd23-81a9-a060-bc0f-b68abdff3c08
* Version Independent ID: be11a039-e151-51fc-68c8-44b46fcc9032
* Content: [Excel.Binding class - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excel/excel.binding)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.binding.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.binding.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @abiarge, 
Sorry for the delay. Events are not supported in Office Scripts. Currently, a script can only be run through the UI or Power Automate. If you'd like events to be added, please create a feature request in [UserVoice](https://excel.uservoice.com/forums/274580-excel-for-the-web?category_id=143439).
I'll be closing the issue, as there's nothing actionable to do in the documentation. If you have further questions, please let me know. Thanks!
