### ISSUE TITLE
Technical terms not useful to end users

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/office-scripts-docs-reference#6]
## Article URL
https://review.docs.microsoft.com/en-us/javascript/api/office-scripts/excel-scripts?branch=master

## Issue
The header 'excel-scripts package' doesn't seem like a useful thing for Office script user. Could we not have this heading?

I also see some text like this in the individual pages:
Package: System.Object[]

Even that I feel is not useful.

**Comment by AlexJerabek** [comment]
This part of OPS's reference documentation system. We should do a comprehensive audit of the changes and present them as a singular effort to our partner teams.

Closing this issue, but created an [internal issue](https://office.visualstudio.com/OC/_workitems/edit/3846330) to track this effort.
