### ISSUE TITLE
Do we need to talk about requirement-sets

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/office-scripts-docs-reference#9]
https://review.docs.microsoft.com/en-us/office/dev/scripts/overview/overview?branch=master#office-javascript-api

Is there a benefit/need to talk about the requirement-sets as its N/A for Office Scripts. 

"...Specifically, they use the APIs available in the ExcelApi Online requirement set. "

**Comment by AlexJerabek** [comment]
Addressed in the office-scripts-docs repo.
