### ISSUE TITLE
Not a lot of detail here

### ISSUE THREAD

**Issue by mhusk** [OfficeDev/office-scripts-docs-reference#95]
Would be great to see an example of using this function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07f33746-5cac-069c-83ce-ea79775bfcf8
* Version Independent ID: e238886e-fa48-00fa-7fe9-2007ccda090f
* Content: [ExcelScript.DeleteShiftDirection enum - Office Scripts](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.deleteshiftdirection?view=office-scripts)
* Content Source: [docs/docs-ref-autogen/excel/excelscript/excelscript.deleteshiftdirection.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/live/docs/docs-ref-autogen/excel/excelscript/excelscript.deleteshiftdirection.yml)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks @mhusk. 
That's a fair statement. I'll get a sample added here sometime soon.
